"""Render stored research reports as downloadable PDF files."""

from __future__ import annotations

from datetime import datetime

from fpdf import FPDF

from app.schemas.research import ResearchReportResponse

DISCLAIMER = (
    "This report is generated by InvestIQ for research and educational purposes only. "
    "It does not constitute investment advice, an offer, or a solicitation to buy or sell "
    "securities. Past performance is not indicative of future results. Consult a qualified "
    "financial advisor before making investment decisions."
)

_ROOT_FOLDER = "InvestIQ Reports"


def build_report_pdf_filename(report: ResearchReportResponse) -> str:
    date_str = report.generated_at.strftime("%Y-%m-%d")
    return f"InvestIQ_{report.ticker}_{date_str}.pdf"


def build_drive_folder_path(ticker: str) -> str:
    return f"{_ROOT_FOLDER}/{ticker.upper()}"


def render_report_pdf(report: ResearchReportResponse) -> bytes:
    pdf = _InvestIQPdf()
    pdf.add_page()

    company = report.financial_data.profile.company_name if report.financial_data else None
    pdf.section_title("InvestIQ Research Report")
    pdf.body_line(f"Ticker: {report.ticker}")
    if company:
        pdf.body_line(f"Company: {company}")
    pdf.body_line(f"Generated: {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}")
    if report.model_used:
        pdf.body_line(f"Model: {report.model_used}")

    rec = report.recommendation
    pdf.section_title("Recommendation")
    if rec:
        pdf.body_line(f"Rating: {rec.rating.value}")
        confidence = report.confidence_score
        if confidence is not None:
            pdf.body_line(f"Confidence: {confidence}%")
        elif rec.confidence_score:
            pdf.body_line(f"Confidence: {rec.confidence_score}%")
        if rec.reasoning:
            pdf.paragraph(rec.reasoning)
    else:
        pdf.body_line("No recommendation issued.")

    committee = report.investment_committee
    if committee:
        pdf.section_title("Investment Committee")
        verdict = committee.verdict
        pdf.body_line(
            f"Verdict: {verdict.final_recommendation.value} "
            f"({verdict.overall_confidence}% confidence)"
        )
        if verdict.investment_horizon:
            pdf.body_line(f"Horizon: {verdict.investment_horizon}")
        if verdict.consensus_summary:
            pdf.paragraph(verdict.consensus_summary)
        if verdict.conclusion:
            pdf.paragraph(verdict.conclusion)

        pdf.section_title("Analyst Views")
        for analyst in committee.analysts:
            pdf.body_line(
                f"{analyst.name} ({analyst.title}): "
                f"{analyst.recommendation.value} - {analyst.confidence}%"
            )
            for point in analyst.supporting_points[:4]:
                pdf.bullet(point)

    pdf.section_title("Financial Summary")
    pdf.paragraph(report.financial_data_summary or "Not available.")

    pdf.section_title("Key Risks")
    risks = rec.risks if rec and rec.risks else []
    if not risks and report.structured_risks:
        risks = report.structured_risks.risks
    if risks:
        for risk in risks[:10]:
            pdf.bullet(risk)
    else:
        pdf.body_line("Not available.")

    pdf.section_title("News Impact")
    pdf.paragraph(report.news_research_summary or "Not available.")

    pdf.section_title("Investment Thesis")
    pdf.paragraph(report.analysis or "Not available.")

    pdf.section_title("Sources")
    sources = _collect_sources(report)
    for source in sources:
        pdf.bullet(source)

    pdf.section_title("Disclaimer")
    pdf.paragraph(DISCLAIMER)

    raw = pdf.output()
    return bytes(raw)


def _collect_sources(report: ResearchReportResponse) -> list[str]:
    sources: list[str] = []
    if report.financial_data and report.financial_data.data_sources:
        sources.extend(f"Yahoo Finance ({s})" for s in report.financial_data.data_sources)
    elif report.financial_data_summary:
        sources.append("Yahoo Finance")
    if report.news_research_summary:
        sources.append("Tavily news")
    if report.guardrails:
        sources.append("InvestIQ guardrails")
    if report.investment_committee and report.investment_committee.sources_used:
        sources.extend(report.investment_committee.sources_used)
    sources.append("OpenRouter LLM agents")
    return sources


class _InvestIQPdf(FPDF):
    def __init__(self) -> None:
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        self.set_margins(15, 15, 15)

    def section_title(self, title: str) -> None:
        self.ln(4)
        self.set_font("Helvetica", "B", 13)
        self.multi_cell(self.epw, 8, _sanitize_pdf_text(title))
        self.ln(1)

    def body_line(self, text: str) -> None:
        self.set_font("Helvetica", "", 10)
        self.multi_cell(self.epw, 6, _sanitize_pdf_text(text))

    def paragraph(self, text: str) -> None:
        self.set_font("Helvetica", "", 10)
        for block in _wrap_text(text):
            self.multi_cell(self.epw, 5, _sanitize_pdf_text(block))
        self.ln(1)

    def bullet(self, text: str) -> None:
        self.set_font("Helvetica", "", 10)
        self.multi_cell(self.epw, 5, f"- {_sanitize_pdf_text(text)}")


def _wrap_text(text: str, max_len: int = 900) -> list[str]:
    cleaned = " ".join(text.split())
    if not cleaned:
        return ["Not available."]
    if len(cleaned) <= max_len:
        return [cleaned]
    chunks: list[str] = []
    start = 0
    while start < len(cleaned):
        chunks.append(cleaned[start : start + max_len])
        start += max_len
    return chunks


def _sanitize_pdf_text(text: str) -> str:
    replacements = {
        "\u2014": "-",
        "\u2013": "-",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2022": "-",
    }
    cleaned = text
    for old, new in replacements.items():
        cleaned = cleaned.replace(old, new)
    return cleaned.encode("latin-1", errors="replace").decode("latin-1")
