"""Render stored research reports as downloadable PDF files."""

from __future__ import annotations

from datetime import datetime

from fpdf import FPDF

from app.schemas.research import ResearchReportResponse

DISCLAIMER = (
    "This report is generated by InvestIQ for research and educational purposes only. "
    "It does not constitute investment advice, an offer, or a solicitation to buy or sell "
    "securities. Past performance is not indicative of future results. Consult a qualified "
    "financial advisor before making investment decisions."
)

_ROOT_FOLDER = "InvestIQ Reports"


def build_report_pdf_filename(report: ResearchReportResponse) -> str:
    date_str = report.generated_at.strftime("%Y-%m-%d")
    return f"InvestIQ_{report.ticker}_{date_str}.pdf"


def build_drive_folder_path(ticker: str) -> str:
    return f"{_ROOT_FOLDER}/{ticker.upper()}"


def render_report_pdf(report: ResearchReportResponse) -> bytes:
    pdf = _InvestIQPdf()
    pdf.add_page()

    company = report.financial_data.profile.company_name if report.financial_data else None
    pdf.section_title("InvestIQ Research Report")
    pdf.body_line(f"Ticker: {report.ticker}")
    if company:
        pdf.body_line(f"Company: {company}")
    pdf.body_line(f"Generated: {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}")
    if report.model_used:
        pdf.body_line(f"Model: {report.model_used}")

    rec = report.recommendation
    pdf.section_title("Recommendation")
    if rec:
        pdf.body_line(f"Rating: {rec.rating.value}")
        confidence = report.confidence_score
        if confidence is not None:
            pdf.body_line(f"Confidence: {confidence}%")
        elif rec.confidence_score:
            pdf.body_line(f"Confidence: {rec.confidence_score}%")
        if rec.reasoning:
            pdf.paragraph(rec.reasoning)
    else:
        pdf.body_line("No recommendation issued.")

    committee = report.investment_committee
    if committee:
        pdf.section_title("Investment Committee")
        verdict = committee.verdict
        pdf.body_line(
            f"Verdict: {verdict.final_recommendation.value} "
            f"({verdict.overall_confidence}% confidence)"
        )
        if verdict.investment_horizon:
            pdf.body_line(f"Horizon: {verdict.investment_horizon}")
        if verdict.consensus_summary:
            pdf.paragraph(verdict.consensus_summary)
        if verdict.conclusion:
            pdf.paragraph(verdict.conclusion)

        pdf.section_title("Analyst Views")
        for analyst in committee.analysts:
            pdf.body_line(
                f"{analyst.name} ({analyst.title}): "
                f"{analyst.recommendation.value} - {analyst.confidence}%"
            )
            for point in analyst.supporting_points[:4]:
                pdf.bullet(point)

    pdf.section_title("Financial Summary")
    financial_lines = _financial_summary_lines(report)
    if financial_lines:
        for line in financial_lines:
            pdf.bullet(line)
    else:
        pdf.body_line("Not available.")

    pdf.section_title("Key Risks")
    risks = rec.risks if rec and rec.risks else []
    if not risks and report.structured_risks:
        risks = report.structured_risks.risks
    if risks:
        for risk in risks[:10]:
            pdf.bullet(risk)
    else:
        pdf.body_line("Not available.")

    pdf.section_title("News Impact")
    news_lines = _news_summary_lines(report)
    if news_lines:
        for line in news_lines:
            pdf.bullet(line)
    else:
        pdf.body_line("Not available.")

    pdf.section_title("Investment Thesis")
    pdf.paragraph(report.analysis or "Not available.")

    pdf.section_title("Sources")
    sources = _collect_sources(report)
    for source in sources:
        pdf.bullet(source)

    pdf.section_title("Disclaimer")
    pdf.paragraph(DISCLAIMER)

    raw = pdf.output()
    return bytes(raw)


# financial_data_summary / news_research_summary are raw JSON blobs built for
# LLM prompt context (see research_formatters.py) - never render them
# directly, or lines like `"ticker": "X",` leak into the PDF. Build
# human-readable lines from the structured fields instead.


def _format_inr_cr(value: float | None) -> str | None:
    if value is None:
        return None
    return f"Rs {value / 1e7:,.2f} Cr"


def _format_ratio_percent(value: float) -> str:
    # ROE/margins arrive as 0-1 fractions from Yahoo Finance.
    pct = value * 100 if abs(value) <= 1 else value
    return f"{pct:.1f}%"


def _financial_summary_lines(report: ResearchReportResponse) -> list[str]:
    fd = report.financial_data
    if fd is None:
        return []
    ratios = fd.ratios[0] if fd.ratios else None
    income = fd.income_statements[0] if fd.income_statements else None

    lines: list[str] = []
    market_cap = _format_inr_cr(fd.profile.market_cap)
    if market_cap:
        lines.append(f"Market cap: {market_cap}")
    if ratios and ratios.return_on_equity is not None:
        lines.append(f"Return on equity: {_format_ratio_percent(ratios.return_on_equity)}")
    if ratios and ratios.net_profit_margin is not None:
        lines.append(f"Net profit margin: {_format_ratio_percent(ratios.net_profit_margin)}")
    if ratios and ratios.debt_to_equity is not None:
        # Already percentage-scale (e.g. 10.5 means debt is 10.5% of equity),
        # not a raw x-multiple - do not run through _format_ratio_percent.
        lines.append(f"Debt-to-equity: {ratios.debt_to_equity:.1f}%")
    if ratios and ratios.current_ratio is not None:
        lines.append(f"Current ratio: {ratios.current_ratio:.2f}")
    if ratios and ratios.price_to_earnings is not None:
        lines.append(f"P/E ratio: {ratios.price_to_earnings:.2f}")
    if ratios and ratios.price_to_book is not None:
        lines.append(f"P/B ratio: {ratios.price_to_book:.2f}")
    revenue = _format_inr_cr(income.revenue) if income else None
    if revenue:
        lines.append(f"Latest revenue: {revenue}")
    net_income = _format_inr_cr(income.net_income) if income else None
    if net_income:
        lines.append(f"Latest net income: {net_income}")
    return lines


def _news_summary_lines(report: ResearchReportResponse) -> list[str]:
    news = report.news_data
    if news is None:
        return []
    lines: list[str] = []
    if news.sentiment_summary:
        lines.append(news.sentiment_summary.strip())
    for group in (news.latest_news, news.earnings_and_filings, news.sector_news):
        for article in group:
            if article.title:
                lines.append(article.title)
            if len(lines) >= 5:
                break
        if len(lines) >= 5:
            break
    return lines


def _collect_sources(report: ResearchReportResponse) -> list[str]:
    sources: list[str] = []
    if report.financial_data and report.financial_data.data_sources:
        sources.extend(f"Yahoo Finance ({s})" for s in report.financial_data.data_sources)
    elif report.financial_data_summary:
        sources.append("Yahoo Finance")
    if report.news_research_summary:
        sources.append("Tavily news")
    if report.guardrails:
        sources.append("InvestIQ guardrails")
    if report.investment_committee and report.investment_committee.sources_used:
        sources.extend(report.investment_committee.sources_used)
    sources.append("OpenRouter LLM agents")
    return sources


class _InvestIQPdf(FPDF):
    def __init__(self) -> None:
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        self.set_margins(15, 15, 15)

    def section_title(self, title: str) -> None:
        self.ln(4)
        self.set_font("Helvetica", "B", 13)
        self.multi_cell(self.epw, 8, _sanitize_pdf_text(title))
        self.ln(1)

    def body_line(self, text: str) -> None:
        self.set_font("Helvetica", "", 10)
        self.multi_cell(self.epw, 6, _sanitize_pdf_text(text))

    def paragraph(self, text: str) -> None:
        self.set_font("Helvetica", "", 10)
        for block in _wrap_text(text):
            self.multi_cell(self.epw, 5, _sanitize_pdf_text(block))
        self.ln(1)

    def bullet(self, text: str) -> None:
        self.set_font("Helvetica", "", 10)
        self.multi_cell(self.epw, 5, f"- {_sanitize_pdf_text(text)}")


def _wrap_text(text: str, max_len: int = 900) -> list[str]:
    cleaned = " ".join(text.split())
    if not cleaned:
        return ["Not available."]
    if len(cleaned) <= max_len:
        return [cleaned]
    chunks: list[str] = []
    start = 0
    while start < len(cleaned):
        chunks.append(cleaned[start : start + max_len])
        start += max_len
    return chunks


def _sanitize_pdf_text(text: str) -> str:
    replacements = {
        "\u2014": "-",
        "\u2013": "-",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2022": "-",
    }
    cleaned = text
    for old, new in replacements.items():
        cleaned = cleaned.replace(old, new)
    return cleaned.encode("latin-1", errors="replace").decode("latin-1")
